Fixes #322, Use the raw property value when the enum does not contain this value
googlesamples/unity-jar-resolver pull request #399
Opened 2020-08-31 19:15 UTC by Zyhlon

This fixes #322 where the unity editor will lose its target sdk setting between unity restarts if you have >28 selected in 2019, since unity AndroidSdkVersions enum does not contain values above 28. 

I have no idea why the function for getting the enum value is so roundabout in the first place, perhaps someone could inform me of why we have to go through the enum type and the string name when we have the correct value from the beginning? Are we expecting the enum int values to diverge from the string values at some point? 

I made minimal impact on the function since I don't understand the purpose of it :)

2020-09-01 08:38 UTC, Zyhlon commented
@googlebot I signed it!

2020-09-09 00:29 UTC, chkuang-g requested changes
Looks good.  Thanks for the fix.

Just apply the suggested modification and it is good to go.

2020-09-09 00:29 UTC, chkuang-g commented on source/AndroidResolver/src/UnityCompat.cs
> +        {
```suggestion
        } catch (ArgumentException) {
```

2020-09-09 08:53 UTC, Zyhlon commented
Done! Do you need me to squash or will you do it in the merge?

2020-09-09 22:45 UTC, merged

2020-09-09 22:45 UTC, chkuang-g commented
Thank you :)