Fix project settings file getting corrupted
googlesamples/unity-jar-resolver pull request #652
Opened 2023-11-06 05:07 UTC by AliAlbarrak

# Why this change?
This resolve the settings file corruption as described in #524

Even though reading and writing of the settings file is protected by a lock, it is possible (due to _domain reload_) that 2 separate running processes are trying to access the file at the same time so the lock in one process is not aware of the other process.

A scenario like this could happen.
1. Code in domain A will start writing to ProjectsSettings file
2. Code in domain B will start reading the file
3. If domain A didn't finish writing yet, domain B will encounter unexpected EOF
4. Domain B will assume the file is broken and reset settings
5. Domain B will write default settings to ProjectsSettings file

# What did I do?
I made the writing happen to a temporary file. When the writing is complete, copy the temp file to the target path. This avoids the file being in an "invalid state" for a short time during the writing.

# Review
Feedback is greatly appreciated and please let me know which steps I need to take to make my change release-ready.

2023-11-14 07:31 UTC, AliAlbarrak commented
As reported [here](https://github.com/googlesamples/unity-jar-resolver/issues/524#issuecomment-1808595188), this fix  fails sometimes so I'll draft the pull request until I find a better solution

2023-12-17 04:51 UTC, AliAlbarrak commented
The settings file gets written multiple times with every domain reload/compile, even when settings didn't change. I added an extra check to skip file write if settings didn't change since last read.

2023-12-24 05:34 UTC, AliAlbarrak commented
Hello @a-maurice @chkuang-g and team
I'd appreciate it if you can guide me through what I need to do to get this reviewed and merged. This PR is associated with the top voted 👍 issue #524. I believe it will be great UX improvement for most users to get it fixed.

2024-01-05 16:28 UTC, cmcpasserby commented
really can non one review this and get it merged in? This issue has been going on for years and makes working with this very annoying and tedious

2024-01-17 13:46 UTC, Tommigun1980 commented
I tested this pull request and my findings are at https://github.com/googlesamples/unity-jar-resolver/issues/524#issuecomment-1895834683

2024-03-01 00:05 UTC, TyelorD requested changes
I think this pull looks good to me, aside from the one change I requested.

That said, I'm not affiliated with Google in any way.

2024-03-01 00:05 UTC, TyelorD commented on source/VersionHandlerImpl/src/ProjectSettings.cs
> +            if (!settings.ContainsKey(name) || settings[name] != stringValue)
To match the current coding style,readability, and portability, this if statement should have enclosing curly braces around the set call for IsModified.

2024-03-01 00:06 UTC, TyelorD commented on source/VersionHandlerImpl/src/ProjectSettings.cs
> +                IsModified = true;
To match the current coding style,readability, and portability, this if statement should have enclosing curly braces around the set call for IsModified.

2024-03-09 22:29 UTC, berniegp commented
Hi! I still got settings corruption with your version. However I think I found the source of the problem and a fix here #678.

2024-05-30 12:55 UTC, alaa13212 commented
I guess this is no longer needed since #678 was merged 🎉

2024-05-30 12:56 UTC, AliAlbarrak commented
I guess this is no longer needed since https://github.com/googlesamples/unity-jar-resolver/pull/678 was merged 🎉

2024-05-30 12:56 UTC, closed without merging